xcodeproj 'Bestmix.xcodeproj'

platform :ios, "7.1"

pod 'AFNetworking', '= 1.0RC1'
pod 'SDURLCache', '~> 1.2a'
pod 'JSONKit', '~> 1.4'
pod 'MBProgressHUD', '~> 0.5'
pod 'TestFlightSDK', '~> 1.1'
pod 'MessagePack', '~> 1.0.0'
pod 'ISO8601DateFormatter', '~> 0.6'
pod 'SVPullToRefresh', '~> 0.3'
pod 'Reachability', '~> 3.0.0'
pod 'MagicalRecord', '~> 2.0.3'
#pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git'
pod 'TPKeyboardAvoiding', '~> 0.0.1'
pod 'SSKeychain', '~> 0.1.4'

